
vehicle_data = [
    {
        "id": 1,
        "license_plate": "NY0001",
        "battery_level": 90,
        "in_use": True,
        "model": "Niu",
        "location_lat": 40.680245,
        "location_long": -73.996955,
        "shift_id": None,
    },
    {
        "id": 2,
        "license_plate": "NY0002",
        "battery_level": 9,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.684978,
        "location_long": -73.998965,
        "shift_id": None,
    },
    {
        "id": 3,
        "license_plate": "NY0003",
        "battery_level": 65,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.683574,
        "location_long": -73.990715,
        "shift_id": None,
    },
    {
        "id": 4,
        "license_plate": "NY0004",
        "battery_level": 34,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.67942,
        "location_long": -73.983841,
        "shift_id": None,
    },
    {
        "id": 5,
        "license_plate": "NY0005",
        "battery_level": 20,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.676695,
        "location_long": -73.988838,
        "shift_id": None,
    },
    {
        "id": 6,
        "license_plate": "NY0006",
        "battery_level": 15,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.675496,
        "location_long": -73.99468,
        "shift_id": None,
    },
    {
        "id": 7,
        "license_plate": "NY0007",
        "battery_level": 90,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.678274,
        "location_long": -73.001642,
        "shift_id": None,
    },
    {
        "id": 8,
        "license_plate": "NY0008",
        "battery_level": 9,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.678434,
        "location_long": -73.997158,
        "shift_id": None,
    },
    {
        "id": 9,
        "license_plate": "NY0009",
        "battery_level": 90,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.683456,
        "location_long": -73.002047,
        "shift_id": None,
    },
    {
        "id": 10,
        "license_plate": "NY0010",
        "battery_level": 22,
        "in_use": True,
        "model": "Niu",
        "location_lat": 40.677941,
        "location_long": -73.982731,
        "shift_id": None,
    },
    {
        "id": 11,
        "license_plate": "NY0011",
        "battery_level": 76,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.673533,
        "location_long": -73.981992,
        "shift_id": None,
    },
    {
        "id": 12,
        "license_plate": "NY0012",
        "battery_level": 90,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.668346,
        "location_long": -73.976115,
        "shift_id": None,
    },
    {
        "id": 13,
        "license_plate": "NY0013",
        "battery_level": 2,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.669861,
        "location_long": -73.989846,
        "shift_id": None,
    },
    {
        "id": 14,
        "license_plate": "NY0014",
        "battery_level": 13,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.673568,
        "location_long": -73.000575,
        "shift_id": None,
    },
    {
        "id": 15,
        "license_plate": "NY0015",
        "battery_level": 17,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.676001,
        "location_long": -73.987382,
        "shift_id": None,
    },
     {
        "id": 16,
        "license_plate": "NY0109",
        "battery_level": 90,
        "in_use": False,
        "model": "Niu",
        "location_lat": 10.683456,
        "location_long": -13.002047,
        "shift_id": None,
    },
    {
        "id": 17,
        "license_plate": "NY0110",
        "battery_level": 22,
        "in_use": False,
        "model": "Niu",
        "location_lat": 10.677941,
        "location_long": -13.982731,
        "shift_id": None,
    },
    {
        "id": 18,
        "license_plate": "NY0111",
        "battery_level": 76,
        "in_use": False,
        "model": "Niu",
        "location_lat": 5.673533,
        "location_long": 5.981992,
        "shift_id": None,
    },
    {
        "id": 19,
        "license_plate": "NY0112",
        "battery_level": 90,
        "in_use": False,
        "model": "Niu",
        "location_lat": 10.668346,
        "location_long": -3.976115,
        "shift_id": None,
    },
    {
        "id": 20,
        "license_plate": "NY0113",
        "battery_level": 2,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.669861,
        "location_long": -73.989846,
        "shift_id": None,
    },
    {
        "id": 21,
        "license_plate": "NY0114",
        "battery_level": 13,
        "in_use": False,
        "model": "Niu",
        "location_lat": 40.673568,
        "location_long": -73.000575,
        "shift_id": None,
    },
    {
        "id": 22,
        "license_plate": "NY0115",
        "battery_level": 17,
        "in_use": False,
        "model": "Niu",
        "location_lat": 10.0,
        "location_long": 10.0,
        "shift_id": None,
    },
    {
        "id": 23,
        "license_plate": "NY0116",
        "battery_level": 100,
        "in_use": False,
        "model": "Niu",
        "location_lat": 10.0,
        "location_long": 10.0,
        "shift_id": None,
    },
    {
        "id": 24,
        "license_plate": "NY0117",
        "battery_level": 10,
        "in_use": False,
        "model": "Niu",
        "location_lat": -100.0,
        "location_long": 10.0,
        "shift_id": None,
    },
        {
        "id": 25,
        "license_plate": "NY0118",
        "battery_level": 10,
        "in_use": False,
        "model": "Niu",
        "location_lat": 10.01,
        "location_long": 10.0,
        "shift_id": None,
    },
]
